name: ESLint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
