name: Build and deploy to GH Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'

      - name: Create Production Build
        run: |
          npm ci
          npm run build

      - name: Deploy with GH-Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
